[package]
name = "nyx-space"
version = "0.1.0-beta2"
edition = "2018"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "A high-fidelity space mission toolkit, with orbit propagation, estimation and some systems engineering"
homepage = "https://nyxspace.com/"
documentation = "https://docs.rs/nyx-space/"
repository = "https://github.com/oakwhiz/nyx-space-apache"
keywords = ["space", "mission", "design", "orbit", "estimation"]
categories = ["science", "simulation"]
readme = "README.md"
license = "Apache-2.0"
exclude = ["tests/GMAT_scripts/GMAT_V&V_ProcessAndResults.pdf", "examples", "data/*.gz", "rustfmt.toml", "de438s.xb"]

[badges]
maintenance = { status = "actively-developed" }
gitlab = { repository = "chrisrabotin/nyx", branch = "master" }

[dependencies]
nalgebra = "0.24"
log = "0.4"
hifitime = "2.2.3"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
serde = "1.0"
serde_derive = "1.0"
csv = "1"
hyperdual = "=0.3.7"
bytes = "1.0"
prost = "0.7"
prost-derive = "0.7"
rand = "0.8"
rand_distr = "0.4"
meval = "0.2"
num = {version = "0.3", default-features = false}
rust-embed = "5.5"
toml = "0.5"
clap = "2"
config = "0.10"
regex = "1.1"
pretty_env_logger = "0.3"
#dialoguer = "0.7"
dialoguer = "0.11"
glob = "0.3"
rayon = "1.5"
lazy_static = "1.4.0"
approx = "0.4"
#bacon-sci = {git = "https://github.com/aftix/bacon", rev="9bae9bf39b33d24bba8e21b6ed2dfab09e3b2ce6"}
bacon-sci = "0.14.0"

[profile.dev]
opt-level = 0
debug = true
